#!/usr/bin/python
# imports - standard imports
import sys, os
import subprocess
import logging
from distutils.spawn import find_executable

logging.basicConfig()
log = logging.getLogger('get-bench')
log.setLevel(logging.DEBUG)

class const(object):
	URL_HOMEBREW_INSTALL  = 'https://raw.githubusercontent.com/Homebrew/install/master/install'
	HOMEBREW_DEPENDENCIES = ['python', 'git', 'mariadb', 'redis', 'node']
	URL_BENCH             = 'https://github.com/frappe/bench'

def which(executable, raise_err = False):
	path = find_executable(executable)

	if not path and raise_err:
		raise ValueError('{executable} not found.'.format(path))
	
	return path

def popen(*params, **kwargs):
	raise_err  = kwargs.get('raise_err')
	proc       = subprocess.Popen(params,
		stdin  = subprocess.PIPE,
		stdout = subprocess.PIPE,
		stderr = subprocess.PIPE)
	
	out, err   = proc.communicate()

	return out

def main(args = None):
	code  = os.EX_OK

	curl  = which('curl',  raise_err = True)
	ruby  = which('ruby',  raise_err = True)
	
	pout  = popen(curl, const.URL_HOMEBREW_INSTALL)
	popen(ruby, '-e', pout)

	brew  = which('brew',  raise_err = True)
	popen(brew, 'install', *const.HOMEBREW_DEPENDENCIES)

	pip   = which('pip',   raise_err = True)
	popen(pip, 'install', '-e', 'git+{github}#egg=frappe-bench'.format(github = const.URL_BENCH))

	return code

if __name__ == '__main__':
	args = sys.argv[1:]
	code = main(args)

	sys.exit(code)